### ISSUE TITLE
Missing message handling in example

### ISSUE THREAD

**Issue by haata** [pentamassiv/zwp-virtual-keyboard#1]
I figured out what was wrong with your example.

You don't process any wayland messages after the initial connection.

```
diff --git a/examples/main.rs b/examples/main.rs
index 0684480..9bd1f03 100644
--- a/examples/main.rs
+++ b/examples/main.rs
@@ -89,11 +89,15 @@ impl VKService {
     }

     // Press and then release the key
-    pub fn submit_keycode(&self, keycode: &str) -> Result<(), SubmitError> {
+    pub fn submit_keycode(&mut self, keycode: &str) -> Result<(), SubmitError> {
         if let Some(keycode) = input_event_codes_hashmap::KEY.get(keycode) {
             let press_result = self.send_key(*keycode, KeyMotion::Press);
+            self.event_queue.sync_roundtrip(&mut (), |_, _, _| println!("UNHANDLED")).unwrap();
             if press_result.is_ok() {
-                self.send_key(*keycode, KeyMotion::Release)
+                std::thread::sleep(std::time::Duration::from_millis(2000));
+                let result = self.send_key(*keycode, KeyMotion::Release);
+                self.event_queue.sync_roundtrip(&mut (), |_, _, _| println!("UNHANDLED")).unwrap();
+                result
             } else {
                 press_result
             }
```

Once I get a better handle on working with the wayland-client crate I'll submit a PR.
Thanks a lot for doing this!

(This code will press the key, hold it for 2 seconds then release; repeat rate works)

**Comment by grelltrier** [comment]
Awesome thank you! I used your suggestions to fix the example. If you have other suggestions, let me know :)

Also I am curious what you will use this crate for? Are you building a virtual keyboard application? I created the crate for my [keyboard](https://github.com/grelltrier/keyboard). It also uses the [input_method](https://github.com/grelltrier/input_method_service) protocol which is much simpler to use if you want to input unicode strings, emoji and stuff like that

**Comment by haata** [comment]
In a nutshell, I'm building a driver extension (HID-IO) for programmable keyboards using the rawhid (hidapi) interface.
The main purpose of zwp-virtual-keyboard will be to type Unicode strings in a cross-platform way (https://github.com/hid-io/hid-io-core/tree/master/src/module/unicode).
Thanks for linking the input_method code! I'll probably stick with using a form of the virtual keyboard, this way I can get repeat rate to work correctly (e.g. assign the Fn+a inside the keyboard to output ß and act just like any other key on the keyboard). This is how it works for X11 as well so might as well keep it similar.
macOS and Windows have something closer (but not the same) as the input_method code so I'm in the process of making some repeat-rate emulation code using the system settings.

HID-IO does a lot of things, has a host-side API, includes support for macro assignments (so you can register scripts that listen for specific macro keys or key events). Integrates with RGB led programs (like https://github.com/antonpup/Aurora).
It'll be one of the shipping features for https://www.kickstarter.com/projects/lekashman/keystone-the-future-of-mechanical-keyboards and will support all Input Club keyboards.

As an FYI, there are quite a few projects out there that would be interested in this code (like this one https://github.com/enigo-rs/enigo/issues/6). It took me a long time to find a succinct example on how to implement a very simple Wayland virtual keyboard. I only realized I code do Unicode with the virtual keyboard (instead of input method) after messing around with squeekboard and noticing how the emoji keyboard worked by using an xkb layout. Thank you so much for this project 👍

**Comment by grelltrier** [comment]
Sounds interesting :)
I assumed squeekboard to do the emojis with the input_method protocol. I should look at it again. I did a very hacky solution to enter them with virtual_keyboard for my keyboard application as a fallback for the input_method protocol. I should probably refactor that then :P
Enigo looks cool too. Maybe I'll change to that down the road for the keyboard application to support other plattforms

**Comment by haata** [comment]
All that's going on with squeekboard is converting the UTF-8 symbol to an xkb keysym. Then map that keysym to a keycode to output. It took me a few days to reason through what they were doing to be sure that's how they were doing it. One odd thing is that you have to convert using a code point rather than using the UTF-8 symbol directly. Basic symbols can be converted directly (like 'a'), but more complicated ones like '💣' need to use the codepoint notation.

```rust
let utf8char = 'a';
let codepoint = format!("U{:04X}", utf8char as u32);
let keysym = xkbcommon::xkb::keysym_from_name(&codepoint.to_string(), xkbcommon::xkb::KEYSYM_NO_FLAGS);
```
